PKIX-Evidence-2025
      { iso(1) identified-organization(3) dod(6) internet(1) 
        security(5) mechanisms(5) pkix(7) id-mod(0) 
        id-mod-pkix-evidence-2025(TBDMOD) }

DEFINITIONS IMPLICIT TAGS ::=
BEGIN

PkixEvidence ::= SEQUENCE {
    tbs                           TbsPkixEvidence,
    signatures                    SEQUENCE SIZE (0..MAX) OF SignatureBlock,
    intermediateCertificates  [0] SEQUENCE OF Certificate OPTIONAL
                                  -- As defined in RFC 5280
}

TbsPkixEvidence ::= SEQUENCE {
    version INTEGER,
    reportedEntities SEQUENCE SIZE (1..MAX) OF ReportedEntity
}

ReportedEntity ::= SEQUENCE {
    entityType         OBJECT IDENTIFIER,
    claims             SEQUENCE SIZE (1..MAX) OF ReportedClaim
}

ReportedClaim ::= SEQUENCE {
    claimType          OBJECT IDENTIFIER,
    value              ClaimValue OPTIONAL
}

ClaimValue ::= CHOICE {
   bytes       [0] OCTET STRING,
   utf8String  [1] UTF8String,
   bool        [2] BOOLEAN,
   time        [3] GeneralizedTime,
   int         [4] INTEGER,
   oid         [5] OBJECT IDENTIFIER,
   null        [6] NULL
}

SignatureBlock ::= SEQUENCE {
   sid                  SignerIdentifier,
   signatureAlgorithm   AlgorithmIdentifier,
   signatureValue       OCTET STRING
}

SignerIdentifier ::= SEQUENCE {
   keyId                [0] EXPLICIT OCTET STRING OPTIONAL,
   subjectKeyIdentifier [1] EXPLICIT SubjectPublicKeyInfo OPTIONAL,
                            -- As defined in RFC 5280
   certificate          [2] EXPLICIT Certificate OPTIONAL
                            -- As defined in RFC 5280
}

PkixEvidenceKeyCapabilities ::= SEQUENCE OF OBJECT IDENTIFIER

id-pkix-evidence OBJECT IDENTIFIER ::= { 1 2 3 999 }

id-pkix-evidence-entity             OBJECT IDENTIFIER ::= { id-pkix-evidence 0 }
id-pkix-evidence-entity-transaction OBJECT IDENTIFIER ::= { id-pkix-evidence-entity 0 }
id-pkix-evidence-entity-platform    OBJECT IDENTIFIER ::= { id-pkix-evidence-entity 1 }
id-pkix-evidence-entity-key         OBJECT IDENTIFIER ::= { id-pkix-evidence-entity 2 }

id-pkix-evidence-claim    OBJECT IDENTIFIER ::= { id-pkix-evidence 1 }

id-pkix-evidence-claim-transaction           OBJECT IDENTIFIER ::= { id-pkix-evidence-claim 0 }
id-pkix-evidence-claim-transaction-nonce     OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-transaction 0 }
id-pkix-evidence-claim-transaction-timestamp OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-transaction 1 }
id-pkix-evidence-claim-transaction-ak-spki   OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-transaction 2 }

id-pkix-evidence-claim-platform            OBJECT IDENTIFIER ::= { id-pkix-evidence-claim 1 }
id-pkix-evidence-claim-platform-vendor     OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 0 }
id-pkix-evidence-claim-platform-oemid      OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 1 }
id-pkix-evidence-claim-platform-hwmodel    OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 2 }
id-pkix-evidence-claim-platform-hwversion  OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 3 }
id-pkix-evidence-claim-platform-hwserial   OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 4 }
id-pkix-evidence-claim-platform-swname     OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 5 }
id-pkix-evidence-claim-platform-swversion  OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 6 }
id-pkix-evidence-claim-platform-debugstat  OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 7 }
id-pkix-evidence-claim-platform-uptime     OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 8 }
id-pkix-evidence-claim-platform-bootcount  OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 9 }
id-pkix-evidence-claim-platform-usermods   OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 10 }
id-pkix-evidence-claim-platform-fipsboot   OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 11 }
id-pkix-evidence-claim-platform-fipsver    OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 12 }
id-pkix-evidence-claim-platform-fipslevel  OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 13 }
id-pkix-evidence-claim-platform-fipsmodule OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-platform 14 }


id-pkix-evidence-claim-key                   OBJECT IDENTIFIER ::= { id-pkix-evidence-claim 2 }
id-pkix-evidence-claim-key-identifier        OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-key 0 }
id-pkix-evidence-claim-key-spki              OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-key 1 }
id-pkix-evidence-claim-key-extractable       OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-key 2 }
id-pkix-evidence-claim-key-sensitive         OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-key 3 }
id-pkix-evidence-claim-key-never-extractable OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-key 4 }
id-pkix-evidence-claim-key-local             OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-key 5 }
id-pkix-evidence-claim-key-expiry            OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-key 6 }
id-pkix-evidence-claim-key-purpose           OBJECT IDENTIFIER ::= { id-pkix-evidence-claim-key 7 }


id-pkix-evidence-key-capability                  OBJECT IDENTIFIER ::= { id-pkix-evidence 2 }
id-pkix-evidence-key-capability-encrypt          OBJECT IDENTIFIER ::= { id-pkix-evidence-key-capability 0 }
id-pkix-evidence-key-capability-decrypt          OBJECT IDENTIFIER ::= { id-pkix-evidence-key-capability 1 }
id-pkix-evidence-key-capability-wrap             OBJECT IDENTIFIER ::= { id-pkix-evidence-key-capability 2 }
id-pkix-evidence-key-capability-unwrap           OBJECT IDENTIFIER ::= { id-pkix-evidence-key-capability 3 }
id-pkix-evidence-key-capability-sign             OBJECT IDENTIFIER ::= { id-pkix-evidence-key-capability 4 }
id-pkix-evidence-key-capability-sign-recover     OBJECT IDENTIFIER ::= { id-pkix-evidence-key-capability 5 }
id-pkix-evidence-key-capability-verify           OBJECT IDENTIFIER ::= { id-pkix-evidence-key-capability 6 }
id-pkix-evidence-key-capability-verify-recover   OBJECT IDENTIFIER ::= { id-pkix-evidence-key-capability 7 }
id-pkix-evidence-key-capability-derive           OBJECT IDENTIFIER ::= { id-pkix-evidence-key-capability 8 }

END